#
//  github-pages.yml
//  
//
//  Created by Ethan Cowan on 4/21/25.
//

name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This fetches complete git history for jekyll-last-modified-at plugin
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
